### ISSUE TITLE
Erreur Scan Wifi (app)

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#51]
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: be.ulb.owl, PID: 4787
java.lang.RuntimeException: Unable to stop activity {be.ulb.owl/be.ulb.owl.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.interrupt()' on a null object reference
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3485)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3531)
    at android.app.ActivityThread.access$1100(ActivityThread.java:156)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:211)
    at android.app.ActivityThread.main(ActivityThread.java:5371)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.interrupt()' on a null object reference
    at be.ulb.owl.Scanner.stopScanTask(Scanner.java:197)
    at be.ulb.owl.graph.Graph.hidden(Graph.java:216)
    at be.ulb.owl.MainActivity.onStop(MainActivity.java:170)
    at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1277)
    at android.app.Activity.performStop(Activity.java:6142)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3482)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3531) 
    at android.app.ActivityThread.access$1100(ActivityThread.java:156) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:211) 
    at android.app.ActivityThread.main(ActivityThread.java:5371) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740) ```

**Comment by detobel36** [comment]
Plus d'actualité :smile:
