### ISSUE TITLE
Bug d'origine inconnue

### ISSUE THREAD

**Issue by denishoornaert** [RobinPetit/OpenWifiLocalizator#63]
```
I/be.ulb.owl.scanner.ScanTask: -------------------------------
I/SurfaceTextureClient: [STC::queueBuffer] (this:0x518fe2e0) fps:37.32, dur:1232.59, max:261.41, min:6.98
I/be.ulb.owl.scanner.ScanTask: Scan has ended
D/SQLiteConnection: executeForCursorWindow took 570ms - succeeded, sql="SELECT DISTINCT Wifi.* FROM Wifi wifi JOIN Wifi joinWifi ON joinWifi.NodeId = wifi.NodeId WHERE joinWifi.BSS IN ('c8:b3:73:02:bb:d6', '18:a6:f7:99:25:22', '00:26:cb:4e:11:20', 'f4:f2:6d:eb:1e:7c', 'a0:1b:29:a6:b2:b4', 'b0:48:7a:db:5b:3a', '00:19:70:3a:9a:e2', 'a4:ee:57:f1:97:0d', '98:de:d0:50:bf:0e', '00:1b:63:2c:64:61', 'e0:ce:c3:d3:9f:f4', 'd4:ca:6d:13:47:30', 'ac:bc:32:cf:a7:37', 'e0:ce:c3:ef:e8:62', '00:26:cb:4e:25:50', '32:91:8f:bf:36:6c', 'd4:ca:6d:11:4a:1d', '98:de:d0:50:79:da', '04:f0:21:16:94:95', 'de:53:60:67:2d:93', '00:12:17:c7:00:03', '58:8b:f3:8b:b3:a8')", window='/data/data/be.ulb.owl/databasesOWL-DB.db {557b0e30}', startPos=0, actualPos=0, filledRows=4974, countedRows=4974
D/be.ulb.owl.utils.SQLUtils: Load wifi: 1
D/be.ulb.owl.graph.Graph: Node found: 3(alias: [Groupe G, Square G, UB])
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40cca9a8)
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.IllegalStateException: Matrix can not be modified
                      at android.graphics.Matrix$1.oops(Matrix.java:43)
                      at android.graphics.Matrix$1.setTranslate(Matrix.java:58)
                      at be.ulb.owl.MainActivity.moveToPoint(MainActivity.java:463)
                      at be.ulb.owl.MainActivity.draw(MainActivity.java:449)
                      at be.ulb.owl.MainActivity.draw(MainActivity.java:431)
                      at be.ulb.owl.graph.Graph.localize(Graph.java:304)
                      at be.ulb.owl.graph.Graph.scanWifiUpdateEvent(Graph.java:317)
                      at be.ulb.owl.scanner.Scanner.newScanFinish(Scanner.java:159)
                      at be.ulb.owl.scanner.ScanTask.onPostExecute(ScanTask.java:95)
                      at be.ulb.owl.scanner.ScanTask.onPostExecute(ScanTask.java:14)
                      at android.os.AsyncTask.finish(AsyncTask.java:631)
                      at android.os.AsyncTask.access$600(AsyncTask.java:177)
                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
                      at android.os.Handler.dispatchMessage(Handler.java:107)
                      at android.os.Looper.loop(Looper.java:194)
                      at android.app.ActivityThread.main(ActivityThread.java:5431)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:525)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                      at dalvik.system.NativeStart.main(Native Method)
I/Process: Sending signal. PID: 22619 SIG: 9
Application terminated.
```
Enjoy !

**Comment by detobel36** [comment]
Je me demande si l'erreur n'est pas le résultat d'un autre problème...  Car quand je fais des tests chez moi ça marche :confused:

**Comment by detobel36** [comment]
Ne c'est jamais reproduit...                 
Je close :stuck_out_tongue:
